USE [master]
GO

/****** Object:  Database [kkkkkkaaaaaa]    Script Date: 2014/09/02 12:52:55 ******/
DROP DATABASE [kkkkkkaaaaaa]
GO

/****** Object:  Database [kkkkkkaaaaaa]    Script Date: 2014/09/02 12:52:55 ******/
CREATE DATABASE [kkkkkkaaaaaa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kkkkkkaaaaaa', FILENAME = N'C:\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\kkkkkkaaaaaa.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'kkkkkkaaaaaa_log', FILENAME = N'C:\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\kkkkkkaaaaaa_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [kkkkkkaaaaaa] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kkkkkkaaaaaa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kkkkkkaaaaaa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET ARITHABORT OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET RECOVERY FULL 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET  MULTI_USER 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kkkkkkaaaaaa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [kkkkkkaaaaaa] SET  READ_WRITE 
GO


